### PR TITLE
Fix: issue #639, if no LORA time source available and GPS time in fir…

### PR DESCRIPTION
**Pull request by oseiler2**
…st call is invalid, then time will never get updated from GPS

https://github.com/cyberman54/ESP32-Paxcounter/issues/639

### CODE REVIEW

**Comment by cyberman54** [comment]
Thanks for this PR and fixing the bug!

What we also could need is a mechanism that syncs unsynced time, as soon as the gps gets a fix.

**Comment by oseiler2** [comment]
I thought the same about triggering the synch from a valid GPS fix, but at the same time if you set TIME_SYNC_INTERVAL_RETRY to 1 minute (which I think is fine when I'm not using any of the LORA time sources) you only need loose 1-2 minutes before getting a valid time synch over setting it directly from a GPS fix.

**Comment by cyberman54** [comment]
@oseiler2 another approach could be adding GPS time sync to `cyclic.cpp`; this routine is called every 30 seconds (`HOMECYCLE` in paxcounter.conf)

**Comment by oseiler2** [comment]
How do you feel about this?
https://github.com/oseiler2/ESP32-Paxcounter/commit/1c40572c9b76a6d9b1431b85ed81c636512f4fd2

**Comment by cyberman54** [comment]
> How do you feel about this?
> [oseiler2@1c40572](https://github.com/oseiler2/ESP32-Paxcounter/commit/1c40572c9b76a6d9b1431b85ed81c636512f4fd2)

@oseiler2 i added some remarks.

**Comment by oseiler2** [comment]
Fair enough, I've done some improvements here: https://github.com/oseiler2/ESP32-Paxcounter/commit/0a510a0c33b64ef360a43d4e01a5fc0d3f1440f0

**Pull request merged**
