### PR TITLE
Documentation for the project with Mkdocs Material

### PR DESCRIPTION
**Pull request by t-huyeng**
Converting the current Readme.md into web page documentation using [mkdocs material](https://squidfunk.github.io/mkdocs-material/). 

- [x] logo draft
- [x] favicon draft 
- [x] github workflow for auto deployment using github pages
- [x] update Readme.md
- [x] added multiple code snippets
- [x] added custom sensor example (#917)
- and more 

Looking forward to any feedback!

See: https://t-huyeng.github.io/ESP32-Paxcounter/ for the running webpage at my fork. 

FYI: local testing/developing of mkdocs material is pretty easy if you have docker installed and running. Just use 
```bash
 docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```
in the root directory of this project. 

If this gets merged GitHub Pages needs to enabled for this project and set to the `github-pages` branch.

### CODE REVIEW

**Review by cyberman54 — COMMENTED** [review]
That looks all good, thank for creation!

One question regarding new file favicon.png: Licence? Or is this free of copyrights?

**Comment by cyberman54** [comment]
>If this gets merged GitHub Pages needs to enabled for this project and set to the github-pages branch.

Done.

**Comment by t-huyeng** [comment]
I created the `favicon.png`, so now copyrights from my side. 

> That looks all good, thank for creation!
> 
> One question regarding new file favicon.png: Licence? Or is this free of copyrights?

**Comment by t-huyeng** [comment]
Thanks for the merge. 

Sadly, the pages build and deployment action is not triggered. (https://github.com/cyberman54/ESP32-Paxcounter/actions/workflows/pages/pages-build-deployment)

This should normally work out of the box automatically.

**Comment by cyberman54** [comment]
What can we do now?

**Comment by t-huyeng** [comment]
I just updated my fork (master) and here the pages deployment gets triggered automatically. 
As far as I can see GitHub Pages should be configured correctly but can you confirm the same setup I have: 

image

**Comment by cyberman54** [comment]
<div class="mt-1 mb-3 px-3" style="box-sizing: border-box; margin-top: var(--base-size-4, 4px)  !important; margin-bottom: var(--base-size-16, 16px)  !important; padding-right: var(--base-size-16, 16px)  !important; padding-left: var(--base-size-16, 16px)  !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mx-0 mx-md-1" style="box-sizing: border-box; margin-right: 0px !important; margin-left: 0px !important;"><h4 class="text-bold" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: var(--h4-size, 16px); font-weight: var(--base-text-weight-semibold, 600)  !important;">Annotations</h4><div class="color-fg-muted text-small" style="box-sizing: border-box; color: var(--color-fg-muted)  !important; font-size: var(--h6-size, 12px)  !important;">1 warning</div></div></div>

deployInput 'emit_telemetry' has been deprecated with message: Use of this input causes the action to do nothing. You should remove this build step from your workflow.
--


Annotations
1 warning
[deploy](https://github.com/cyberman54/ESP32-Paxcounter/actions/runs/3526728428/jobs/5915000915#step:2:1)
Input 'emit_telemetry' has been deprecated with message: Use of this input causes the action to do nothing. You should remove this build step from your workflow.

**Comment by t-huyeng** [comment]
> #### Annotations
> 1 warning
> ## deployInput 'emit_telemetry' has been deprecated with message: Use of this input causes the action to do nothing. You should remove this build step from your workflow.
> Annotations 1 warning [deploy](https://github.com/cyberman54/ESP32-Paxcounter/actions/runs/3526728428/jobs/5915000915#step:2:1) Input 'emit_telemetry' has been deprecated with message: Use of this input causes the action to do nothing. You should remove this build step from your workflow.

This should not be a problem.  I have the same warning, and also this workflow is from GitHub itself.

**Comment by t-huyeng** [comment]
> What can we do now?
Maybe you could force rebuild with a simple change of something in the docs and commit directly to the master branch. 

Or maybe it has something todo with the github-pages branch existing before.

I try to find out more.

**Comment by cyberman54** [comment]
settings looks identical.
I kicked off a re-run manually.
Still no deployment.

**Comment by t-huyeng** [comment]
Okay. 
I think rerunning is not using the current version of the branch, but noch 100% sure. 

The branch looks good: https://github.com/cyberman54/ESP32-Paxcounter/tree/gh-pages
So mkdocs deployment was successful. Something is not working with the github pages build/deployment.

**Comment by cyberman54** [comment]
Here's the extended log of run:
https://github.com/cyberman54/ESP32-Paxcounter/actions/runs/3526728428/jobs/5921923721

**Comment by t-huyeng** [comment]
Its working!

**Comment by t-huyeng** [comment]
If you want you can add the docs link to the about section like I have on my fork:
image

**Pull request merged**
