### PR TITLE
Added new board and LED Matrix display

### PR DESCRIPTION
**Pull request by vyruz1986**
This PR adds a new board (Wemos32 with built-in OLED display) and a 64x16 pixels LED Matrix display.

We (Hackerspace Brixel) used this project with said display to keep count of people who visited our booth at Maker Faire Gent (Belgium) 2019. We configured `cfg.countermode = 1` in https://github.com/cyberman54/ESP32-Paxcounter/blob/master/src/configmanager.cpp#L18 in order to keep counting visitors throughout the whole weekend.

FYI: The counter ran from Saturday morning until Sunday evening, and reached a count of 1720. I was affraid it would crash due to the memory limit of the ESP32, but it seems that limit is higher than I anticipated.

### CODE REVIEW

**Comment by vyruz1986** [comment]
Sure, I've attached 2 images below. The 'enclosure' (cardboard box) had some info on it (including the github link to your this repo, giving credit where due :) ). 

One thing I forgot to mention: Currently the display only shows the total PAX number (`macs.size()`), and no other information. I didn't have time to put more info on the display. It's also not the easiest display to drive: the SeedStudio library takes a display buffer as argument, and takes care of putting that buffer on the actual display, however putting any information (text, drawings, etc..) in the display buffer needs to be done manually.

IMG_20190505_181230
IMG_20190505_100216

**Comment by cyberman54** [comment]
> One thing I forgot to mention: Currently the display only shows the total PAX number (`macs.size()`), and no other information. I didn't have time to put more info on the display. It's also not the easiest display to drive: the SeedStudio library takes a display buffer as argument, and takes care of putting that buffer on the actual display, however putting any information (text, drawings, etc..) in the display buffer needs to be done manually.
> 

Since this is a controller-less display which thus has do be multiplexed by external CPU, it would be great to use the PWM functions of ESP32 for multiplexing; keeping the paxcounter software free of the scan task.

**Comment by cyberman54** [comment]
@vyruz1986 i merged your PR into development branch of paxcounter repo.
I made some small changes and pushed them as version 1.7.61 in development branch.
Could you please retest this version and check if your matrix display still works? Thanks.

PS: What type of LED matrix pcb should in buy to build up a test installation?

/cc @spmrider

**Comment by vyruz1986** [comment]
Compilation fails due to removal of `extern uint8_t MatrixDisplayIsOn;` in main.cpp.
I added a inline comment on the diff of this PR.

I bought this display on AliExpress 2 years ago, sadly the exact article I bought is not available anymore.
I'm pretty sure though that this will be the same type: 
https://www.aliexpress.com/item/P3-75-dot-matrix-led-module-3-75mm-high-clear-top1-for-text-display-304-60mm/32616683948.html?spm=2114.search0104.3.14.7864690fbZxOK6&ws_ab_test=searchweb0_0,searchweb201602_8_10065_10068_319_317_10696_10084_453_10083_454_10618_10304_10307_10820_10821_537_10302_536_10843_10059_10884_10887_321_322_10103,searchweb201603_52,ppcSwitch_0&algo_expid=a54d0d08-dc18-47cf-b72f-50debc5d21cb-2&algo_pvid=a54d0d08-dc18-47cf-b72f-50debc5d21cb&transAbTest=ae803_3

**Comment by cyberman54** [comment]
should be fixed now.
I ordered that display on ali, now waiting for arrival. thanks for the hint & your code!

**Pull request merged**
