### PR TITLE
Change Display PIN

### PR DESCRIPTION
**Pull request by FabTangi**
Proposed change to make display OK on TTGO T-Beam V1.1

### CODE REVIEW

**Comment by cyberman54** [comment]
I don't the impact of this change, since SDA and SDL are defined in pins_arduino.h with same values?

**Comment by FabTangi** [comment]
Well, on my side this solved the issue on display. Where is pins_arduino.h located?

**Comment by cyberman54** [comment]
Please check your toolchain, i.e. correct version (see platformio.ini) of arduino-esp32 (contains pins_arduino.h) installed.

**Comment by FabTangi** [comment]
You're completly rigth, after cleaning up ome old esp32 definitions, it is working with master branch.

**Pull request closed without merging**
