### PR TITLE
Fix/cleanup of packed decoder code

### PR DESCRIPTION
**Pull request by TD-er**
This is a PR to your development branch, so you can later decide if it can be merged to master.

### CODE REVIEW

**Comment by cyberman54** [comment]
Thanks!

**Comment by cyberman54** [comment]
fixed.

**Comment by TD-er** [comment]
Where did I miss it?

**Comment by cyberman54** [comment]
https://github.com/cyberman54/ESP32-Paxcounter/commit/9ad6e62e84c7aed8e08af914167374a1c51b6115

**Comment by TD-er** [comment]
Ah, yep that should make a difference :)

**Pull request merged**
