### PR TITLE
lorawan-device repo initial files

### PR DESCRIPTION
**Pull request by Drasek**
This includes all the initial files necessary for a first realease in the lorawan-devices repo [https://github.com/TheThingsNetwork/lorawan-devices](https://github.com/TheThingsNetwork/lorawan-devices). I though it would be best to include this here into the repo, so we can work on it together till its ready to release, then follow the steps below to include it into the lorawan-devices repo. If we change stuff in the future (maybe sensor data like pm25 and pm10 on port 10 and such things), we need to change the payload decoder, the examples, etc. and we can do this here together and one of us will update the lorawan-device repo from time to time (after each release with changes to the payload, or things related to the repo).

Things to talk about:
- name of the vendor (we need one!), i used "opensource" for the id (lowercase, dashes only) and "Open Source Community Projects" as name, so that other bigger community projects could use the same vendor to add their devices to the lorawan-device repo.
- name of the device - "ESP32-Paxcounter" (name) and "esp32-paxcounter" (id) is used, because thats the name of this repo and as such it will be easily found from users.

How to add the files to the repo:
- clone the repo
- add the marked lines from the index.yaml to the end of the original index.yaml
- create the folder opensource inside the vendor folder
- copy all the files from this vendor/opensource to the new vendor/opensource folder
- make a pull request

If we want we can add a image. I don't know wether the licence is CC0 or such, so i have not included one atm, if you want to include one, tell me which and i add it.

### CODE REVIEW

**Comment by cyberman54** [comment]
@spmrider could you take a closer look at this?

**Comment by oliverbrandmueller** [comment]
> @spmrider could you take a closer look at this?

I do have that on my list; however due to summer holidays it's unlikely this is before mid july.

**Comment by Drasek** [comment]
If you want, we can set up a call, so i can explain more easily why i did what i did and you have more details to decide about how to move on with this.

**Comment by Drasek** [comment]
One of the reasons to support the lorawan-device repo was the 4k limit of the payload decoder in the ttn v3, this is under discussion again: [https://github.com/TheThingsNetwork/lorawan-stack/issues/4278#issuecomment-864061169](https://github.com/TheThingsNetwork/lorawan-stack/issues/4278#issuecomment-864061169) - could take a while (its marked with Q3 release).

The other reason for the lorawan-device repo is that it is more convenient for users just to choose a vendor/device and things like the lorawan version and the payload decoder is set automaticly.

**Comment by cyberman54** [comment]
@Drasek i merged this to master, thank you! Could you open the pull request on TTN side?

**Comment by Drasek** [comment]
Great! I will open the pull request on TTN side.

**Comment by cyberman54** [comment]
@Drasek Sometimes i see "missing codec" entries in the LiveMessage Console. Probably this happenes when MAC commands are delivered. Is there a way to enhance the decoder to display the payload / MAC commands?

image

**Pull request merged**
