### PR TITLE
[AXPxxx] Add support for AXP2101 and AXP202

### PR DESCRIPTION
**Pull request by TD-er**
Split the code into several sections for AXP192/AXP2101/AXP202

ToDo:
- [ ] Test AXP192 on real hardware
- [ ] Test AXP2101 on real hardware
- [ ] Test AXP202 on real hardware
- [ ] Add more defines/boards using these chips
- [ ] Add defines on which LDO/DC ports should be enabled/disabled to be used in board .h files.

The code for AXP192 should not have changed, so that should probably be safe to use.

**_!!!The other chips have absolutely NOT been tested on real hardware!!!_**

Status: "it compiles"

**Do NOT run this on real hardware unless you really know what to check for your board!**

Fixes: #990

### CODE REVIEW

**Comment by TD-er** [comment]
@cyberman54 
Please note the state of this code is "it compiles".
So please have a very thorough look before uploading it to some board as I really hope I did not mess up.

**Comment by cyberman54** [comment]
Thanks for this work. Merged to new temporary development branch "feature-axp2101". Using for testing.

**Comment by TD-er** [comment]
Will you continue from here?
Or should I try to tweak some more? (from that branch)

**Comment by cyberman54** [comment]
please use the feature-axp2102 branch, i will continue and test from here. First, will merge the experimental tsupremes3.hal from development branch with your axp20xx.hal, then check voltages for T-Supreme, and then give it a try.

**Comment by TD-er** [comment]
Please double/triple check to see if I do  toggle the correct DCDC/LDO channels

**Comment by cyberman54** [comment]
> Please double/triple check to see if I do toggle the correct DCDC/LDO channels

Meanwhile, i found some prior art here:
https://github.com/meshtastic/firmware/blob/master/src/Power.cpp#L843

This should work, because the purchased T-Beam Supreme S3 came with working Meshtastic firmware preinstalled.

**Comment by cyberman54** [comment]
@TD-er took me a long time, but now Xpowers Lib ist fully integrated and code renovated.

**Comment by TD-er** [comment]
In the mean time, I also implemented support for this chip [in ESPEasy](https://espeasy.readthedocs.io/en/latest/Plugin/P139.html#p139-page). :)

I'm quite impressed by the e-gauge feature to determine batter charge level.

**Pull request merged**
