### PR TITLE
Update ttgov1.h

### PR DESCRIPTION
**Pull request by DierkJ**
issue #577:  Pin DIO2 of SX1276 is connected to pin 32

### CODE REVIEW

**Comment by cyberman54** [comment]
Are you sure that this matches the TTGO T1 board?
Please post exact type and picture of your board.
The first TTGO boards did not have DIO1 and DIO2 connected.

**Comment by DierkJ** [comment]
Hi Cyberman,

this is my TTGO Lora32 board.
I will double check the wiring with a multimeter later today.   Stuck with COVID 19 phone conferences…

best regards,
Dierk

**Comment by DierkJ** [comment]
Hi Cyberman,

ich hab’s gerade durchgeklingelt.  Pin9 vom SX1276 ist mit Pin12 vom ESP verbunden.


viele Grüße aus München,
Dierk

**Comment by cyberman54** [comment]
@DierkJ please post a link to a picture of the board you are using, thanks.

**Pull request merged**
