### PR TITLE
Implemented ABP configuration (on development branch)

### PR DESCRIPTION
**Pull request by nuthub**
Follow-Up / Replace of PR #497

### CODE REVIEW

**Comment by nuthub** [comment]
The relevant code snippets are from LMIC library examples, where the netid is hardcoded as well. More on the netid parameter can be found here: https://lora-alliance.org/sites/default/files/2018-11/20181114_NetID_FAQ.pdf .

For the other requests: The purpose of the modification was - in my case - to avoid pending join attempts, which where annoying during some coding. Now that you enhanced the code according to #60, this might be enough. However, I don't have any hardware at the moment to test something. Therefore, I postpone the further enhancement until I feel the need and mood for it.

**Comment by cyberman54** [comment]
> Now that you enhanced the code according to #60, this might be enough. However, I don't have any hardware at the moment to test something. Therefore, I postpone the further enhancement until I feel the need and mood for it.

I think your ABP enhancement is a good add on. But we need to add the remaining network parameter settings, i.e. a channel map. Otherwise the node will use only 3 channels. And please think of global usage of this software, so we need a solution which can be tailored to different country parameter settings, not only EU868.

**Comment by nuthub** [comment]
Hi, I got some hardware again and started working on ABP integration again. Please have a look at the commit.

I thought about three options to incorporate your requests:
1. Add a macro function to loraconf.h -> ugly, odd syntax, bad maintainability, etc
2. Add another cpp file (loraconf_abp.cpp) to configure channel map and additional parameters -> most flexible way, additional parameters can be set there. Still, some parameters could be set in loraconf.h
3. Add some data structure to loraconf.h to configure channel map and additional parameters -> any opinion / suggestion on that?

**Comment by cyberman54** [comment]
Thanks for the PR. I peeked into already, will do a closer look next days.
I am still not sure if it's a good idea to implement ABP for usage in non-private networks.

**Comment by nuthub** [comment]
Hi, why are you not sure, if it is a good a idea to implement ABP?

**Comment by cyberman54** [comment]
As @terrillmoore , maintainer of MCCI LMIC states:
"If using a completely private network, ABP is ok; but on a standards-based network, it is very hard with cheap hardware to achieve the strict requirements of the spec related to reuse of FCntUp."

**Comment by nuthub** [comment]
You are true that in production and whenever possible one should use OTAA. But there are also setups in which ABP might be useful, like development phase or short time use of a PaxCounter, just because (re-)joining does take some time.

Regarding FCntUp (and FCntDown): Instead of disabling frame counter checks at all, one could reset the frame counter on network/application side whenever a node is restarted that does not store the FCntUp.

What do you think about clearly stating that OTAA should be used in normal, especially in production scenarios and ABP should only be used where OTAA is not suitable? And to also mention (or link to) the implications like https://www.thethingsnetwork.org/docs/devices/registration.html ?

Of course, in the end it's up to you to decide, whether to include the patch or not. At least one user of the software (me :) ) thinks that this would be a good add on.

**Comment by cyberman54** [comment]
I will include it, since this is a development / hackers platform, and no commercial software download store. So please keep going, but please create a clean version which at least deals with proper settings for joining and re-joining the network.

Regarding FCntUp (and FCntDown): these are counters on the network server, which usually can't be modified by a user's application.

**Comment by cyberman54** [comment]
@nuthub could you please update readme.md? Thanks

**Pull request merged**
