### PR TITLE
Fixed validation errors and got us pulled into the lorawan-devices repo

### PR DESCRIPTION
**Pull request by Drasek**
I had some errors in the original pull request to the lorawan-devices error wich i fixed:

- fixed byte order in the esp32-paxcounter.yaml to make it validate (lsb vs msb) and added some real world examples
- commented out some sensor types because they are not yet support officially in their repo (ble, wifi, pax - will try to get them added later)
- changed decoder file name to esp32-paxcounter-packed.js because no uppercase is allowed

Got the pull request accepted with these changes: [https://github.com/TheThingsNetwork/lorawan-devices/commit/2b2f57039a3b264e9f8d261573a1a603056751f9](https://github.com/TheThingsNetwork/lorawan-devices/commit/2b2f57039a3b264e9f8d261573a1a603056751f9)

Now we have to wait till they update the backend the network server. I will add further instructions to the readme.md how to use  the new v3 console to add a paxcounter to a application, once its added.

### CODE REVIEW

**Comment by cyberman54** [comment]
Thanks a lot!

**Comment by cyberman54** [comment]
@Drasek Do you know how often those updates of TTN backend happen? (How long will we have to wait?)

**Comment by Drasek** [comment]
I asked Jaime int eh lorawan-device repo about it and i am waiting for a answer. Atm the community edition is updated roughly every 2 weeks (thats if i look at the date stamps of the release commits) and we are 5 days into the cycle - could be around 10 days if its with the next release (3.13.4 should be the next).

**Comment by Drasek** [comment]
We are in the actual version 3.14.0 of the things v3 stack and online in the ttn community edition! I have not realy tested it so far, will do so on the weekend and write a manual in the readme.md how to use it in the ttn v3 console.

**Pull request merged**
