### PR TITLE
Generic Temperature and Humidty PayloadConvert functions

### PR DESCRIPTION
**Pull request by t-huyeng**
I was looking for an easy way to send temperature and humidity data. Since I did not find the right `PayloadConvert` for this, I just added one. 

This function can be used for any user specific sensor which measures temperature and humidity.

@cyberman54 what are your thoughts on suche generic function? 

FYI: I currently tested only the packed format function.

### CODE REVIEW

**Comment by t-huyeng** [comment]
Since all checks (github action) are starting for this pull-request I think we could also change the workflow again that only a few boards get tested  during a pull request. 

What about:
- ttgov21new.h
- generic.h
- heltecv21.h

Or any other boards?

**Comment by cyberman54** [comment]
Yes, we can merge this, no problem.
But wouldn't it be kind of dead code without a sensor usecase & hal file?

**Comment by t-huyeng** [comment]
Yes that is probably true. I could add the function as a comment in the [sensor.cpp](https://github.com/cyberman54/ESP32-Paxcounter/blob/master/src/sensor.cpp#L45).  This still means that the code is not really used. 

I used it for my gy21 see [this](https://github.com/t-huyeng/ESP32-Paxcounter/blob/gy21-sensor/src/sensor.cpp#L88).

Maybe an example for a custom sensor would also be at least a start (in the readme or in an extra example folder ).

**Comment by t-huyeng** [comment]
I see what you mean and I think you are right. 
For me it would also be okay if we do not merge this (this is why a made this a draft as well). I will try to work on an example in the next days and maybe we can just leave this in my fork and add it to the readme here or something like that. 

I am actually using this project as a "template" since I feel there is no better project with so many configuration out there.

**Comment by t-huyeng** [comment]
I added and update most of this code to the docs.
See: https://t-huyeng.github.io/ESP32-Paxcounter/configuration/custom-sensors/
or: https://github.com/t-huyeng/ESP32-Paxcounter/blob/mkdocs/docs/configuration/custom-sensors.md

So I would suggest to close this PR and keep the code in the docs.

**Comment by cyberman54** [comment]
ok & thx!

**Pull request closed without merging**
